In [1]:
# Importar librerías

import pandas as pd
import numpy as np
import csv
from bs4 import BeautifulSoup
from datetime import datetime
import time
from time import sleep
import math
from textblob import TextBlob

# Librerías de Selenium

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

# Translator

from googletrans import Translator, constants
translator = Translator()

In [5]:
# Twitter

def get_n_tweets(n, search_str='Covid 19'):
    option = Options()
    option.headless = False
    driver = webdriver.Chrome(options=option)
    
    driver.get("http://twitter.com/search?q=%24" + search_str + "&src=typeahead_click&f=top")
    driver.maximize_window()

    response = []
    for x in range(math.ceil(n / 10)):
        print(x)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)
        try:
            WebDriverWait(driver, 5).until(
                EC.presence_of_element_located((By.CSS_SELECTOR, "div[class='css-1dbjc4n r-1iusvr4 r-16y2uox r-1777fci r-kzbkwu']"))
            )

            e_tweets = driver.find_elements(By.CSS_SELECTOR, "div[class='css-1dbjc4n r-1iusvr4 r-16y2uox r-1777fci r-kzbkwu']")
            #print(len(e_tweets))

            for e_tweet in e_tweets:
                counter = 0
                while True:
                    try:
                        e_fullname = e_tweet.find_element(By.CSS_SELECTOR, "div>span[class='css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0']")
                        e_tweet_text = e_tweet.find_element(By.CSS_SELECTOR, "div[class='css-901oao r-18jsvk2 r-37j5jr r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-bnwqim r-qvutc0']")
                        e_tweet_date = e_tweet.find_element(By.CSS_SELECTOR, "a>time")
                        response.append({'date': e_tweet_date.text,'by': e_fullname.text,
                                         'tweet': e_tweet_text.text,
                                         'score': TextBlob(translator.translate(e_tweet_text.text).text).sentiment.polarity}),
                                         
                        break
                    except:
                        if counter < 1:
                            counter += 1
                            print(f'Failed to scrape {e_tweets.index(e_tweet)}. Trying again in 5 seconds.')
                            sleep(5)
                            continue
                        else:
                            break
        finally:
            continue
    driver.quit()
    return response

In [6]:
# Obteniendo las noticias

tag = "BTC"
tweets = get_n_tweets(500 ,tag)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124

In [7]:
tweets_df = pd.DataFrame(tweets)
tweets_df

,date,by,tweet,score
0,24min,@CromLucas,Mi pregunta para la gente que le teme a entrar...,0.0
1,17 dic.,@cryptobcncat,“No permitáis que tus familiares cambien de te...,0.0
2,15 dic.,@altcoinrookie,$BTC #Bitcoin \nKesin böyle olcak bak! Al ekra...,0.0
3,5 dic.,@DaanCrypto,$BTC Is looking like a miniature version of th...,0.1
4,24 oct.,@CryptoBoBuilder,1 week and 4hours almost like copy and paste,0.0
...,...,...,...,...
1250,17 dic.,@carlos_GA,"No diré $BTC porque sería evidente, aunque mi ...",0.0
1251,17 dic.,@JuanuMusic,El cashback del 2% de \n@lemonapp_ar\n en $BTC...,0.9
1252,10h,@BotDolarBlue,La cotización del BITCOIN TREPA a $47K \n\n#B...,0.0
1253,17 dic.,@BotDolarBlue,La cotización del BITCOIN CAE a $45K \n\n$BTC...,0.0
1254,16 dic.,@NOTaWHALE12,$btc\nLo único que falta es mucho capital apal...,0.0

In [8]:
tweets_df.to_excel("tweets.xlsx")

In [13]:
# Eliminar duplicados

print(tweets_df.tweet.duplicated().value_counts())
df_clean = tweets_df[tweets_df.tweet.duplicated() == False]
df_clean

True     1087
False     168
Name: tweet, dtype: int64

,date,by,tweet,score
0,24min,@CromLucas,Mi pregunta para la gente que le teme a entrar...,0.0
1,17 dic.,@cryptobcncat,“No permitáis que tus familiares cambien de te...,0.0
2,15 dic.,@altcoinrookie,$BTC #Bitcoin \nKesin böyle olcak bak! Al ekra...,0.0
3,5 dic.,@DaanCrypto,$BTC Is looking like a miniature version of th...,0.1
4,24 oct.,@CryptoBoBuilder,1 week and 4hours almost like copy and paste,0.0
...,...,...,...,...
220,17 dic.,@carlos_GA,"No diré $BTC porque sería evidente, aunque mi ...",0.0
221,17 dic.,@JuanuMusic,El cashback del 2% de \n@lemonapp_ar\n en $BTC...,0.9
222,10h,@BotDolarBlue,La cotización del BITCOIN TREPA a $47K \n\n#B...,0.0
223,17 dic.,@BotDolarBlue,La cotización del BITCOIN CAE a $45K \n\n$BTC...,0.0
224,16 dic.,@NOTaWHALE12,$btc\nLo único que falta es mucho capital apal...,0.0

In [14]:
from translate import translate

translations = translate(df_clean.tweet)

Failed to scrape. Trying again in 5 seconds.
Failed to scrape. Trying again in 5 seconds.